### PR TITLE
Handle NaN and Infinity when encoding the native AST

### LINKED ISSUE #51: Inf and Nan cannot be JSON encoded
In the latest [bblfsh logs](https://github.com/bblfsh/bblfshd/issues/298) we encountered the following error:

```
rpc error: code = Internal desc = Error#7, Inf and NaN cannot be JSON encoded
```

Files that triggered the error:

```
vendor/symfony/yaml/Symfony/Component/Yaml/Tests/InlineTest.php
lib/composer/symfony/yaml/Symfony/Component/Yaml/Tests/InlineTest.php
hphp/test/slow/print/1445.php
hphp/test/slow/unary_operators/1436.php
hphp/test/zend/bad/tests/lang/bug24640.php
hphp/test/slow/json/1552.php
hphp/test/slow/print/1441.php
hphp/test/slow/print/1443.php
hphp/test/slow/print/1447.php
hphp/test/zend/good/ext/standard/tests/general_functions/bug27678.php
```

### PR DESCRIPTION
**Pull request by dennwc**
Encoding NaN and infinity values currently leads to encoding error. This PR fixes it by replacing those values with a string representation. 

Fixes #51

Signed-off-by: Denys Smirnov <denys@sourced.tech>

---
This change is [Reviewable](https://reviewable.io/reviews/bblfsh/php-driver/61)

### CODE REVIEW

File: native/src/AstExtractor/Formatter/Json.php [hunk 1]
```diff
@@ -87,6 +87,17 @@ public function readNext()
...
+        if (is_numeric($input)) {
+            if (is_nan($input)) {
+                $input = "NaN";
+            } else if (is_infinite($input)) {
+                if ($input > 0) {
+                    $input = "+Inf";
+                } else {
+                    $input = "-Inf";
+                }
+            }
```
Comment (kuba--) [inline native/src/AstExtractor/Formatter/Json.php]: btw. can we return here.

Comment (dennwc) [reply native/src/AstExtractor/Formatter/Json.php]: Sure, will change it.

Comment (dennwc) [reply native/src/AstExtractor/Formatter/Json.php]: Done!
